/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LangchainChatImport } from './routes/langchain-chat'
import { Route as ChatImport } from './routes/chat'
import { Route as IndexImport } from './routes/index'
import { Route as TranslateIndexImport } from './routes/translate/index'
import { Route as KnowledgeIndexImport } from './routes/knowledge/index'
import { Route as KnowledgeIdImport } from './routes/knowledge/$id'
import { Route as ChatChatImport } from './routes/chat/_chat'
import { Route as LangchainChatLangchainChatIndexImport } from './routes/langchain-chat/_langchain-chat.index'
import { Route as ChatChatIndexImport } from './routes/chat/_chat.index'
import { Route as LangchainChatLangchainChatIdImport } from './routes/langchain-chat/_langchain-chat.$id'
import { Route as ChatChatIdImport } from './routes/chat/_chat.$id'

// Create/Update Routes

const LangchainChatRoute = LangchainChatImport.update({
  path: '/langchain-chat',
  getParentRoute: () => rootRoute,
} as any)

const ChatRoute = ChatImport.update({
  path: '/chat',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TranslateIndexRoute = TranslateIndexImport.update({
  path: '/translate/',
  getParentRoute: () => rootRoute,
} as any)

const KnowledgeIndexRoute = KnowledgeIndexImport.update({
  path: '/knowledge/',
  getParentRoute: () => rootRoute,
} as any)

const KnowledgeIdRoute = KnowledgeIdImport.update({
  path: '/knowledge/$id',
  getParentRoute: () => rootRoute,
} as any)

const ChatChatRoute = ChatChatImport.update({
  id: '/_chat',
  getParentRoute: () => ChatRoute,
} as any)

const LangchainChatLangchainChatIndexRoute =
  LangchainChatLangchainChatIndexImport.update({
    path: '/',
    getParentRoute: () => LangchainChatRoute,
  } as any)

const ChatChatIndexRoute = ChatChatIndexImport.update({
  path: '/',
  getParentRoute: () => ChatChatRoute,
} as any)

const LangchainChatLangchainChatIdRoute =
  LangchainChatLangchainChatIdImport.update({
    path: '/$id',
    getParentRoute: () => LangchainChatRoute,
  } as any)

const ChatChatIdRoute = ChatChatIdImport.update({
  path: '/$id',
  getParentRoute: () => ChatChatRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatImport
      parentRoute: typeof rootRoute
    }
    '/langchain-chat': {
      id: '/langchain-chat'
      path: '/langchain-chat'
      fullPath: '/langchain-chat'
      preLoaderRoute: typeof LangchainChatImport
      parentRoute: typeof rootRoute
    }
    '/chat/_chat': {
      id: '/chat/_chat'
      path: ''
      fullPath: '/chat'
      preLoaderRoute: typeof ChatChatImport
      parentRoute: typeof ChatImport
    }
    '/knowledge/$id': {
      id: '/knowledge/$id'
      path: '/knowledge/$id'
      fullPath: '/knowledge/$id'
      preLoaderRoute: typeof KnowledgeIdImport
      parentRoute: typeof rootRoute
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeIndexImport
      parentRoute: typeof rootRoute
    }
    '/translate/': {
      id: '/translate/'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof TranslateIndexImport
      parentRoute: typeof rootRoute
    }
    '/chat/_chat/$id': {
      id: '/chat/_chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatChatIdImport
      parentRoute: typeof ChatChatImport
    }
    '/langchain-chat/_langchain-chat/$id': {
      id: '/langchain-chat/_langchain-chat/$id'
      path: '/$id'
      fullPath: '/langchain-chat/$id'
      preLoaderRoute: typeof LangchainChatLangchainChatIdImport
      parentRoute: typeof LangchainChatImport
    }
    '/chat/_chat/': {
      id: '/chat/_chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatChatIndexImport
      parentRoute: typeof ChatChatImport
    }
    '/langchain-chat/_langchain-chat/': {
      id: '/langchain-chat/_langchain-chat/'
      path: '/'
      fullPath: '/langchain-chat/'
      preLoaderRoute: typeof LangchainChatLangchainChatIndexImport
      parentRoute: typeof LangchainChatImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ChatRoute: ChatRoute.addChildren({
    ChatChatRoute: ChatChatRoute.addChildren({
      ChatChatIdRoute,
      ChatChatIndexRoute,
    }),
  }),
  LangchainChatRoute: LangchainChatRoute.addChildren({
    LangchainChatLangchainChatIdRoute,
    LangchainChatLangchainChatIndexRoute,
  }),
  KnowledgeIdRoute,
  KnowledgeIndexRoute,
  TranslateIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/chat",
        "/langchain-chat",
        "/knowledge/$id",
        "/knowledge/",
        "/translate/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/chat": {
      "filePath": "chat.tsx",
      "children": [
        "/chat/_chat"
      ]
    },
    "/langchain-chat": {
      "filePath": "langchain-chat.tsx",
      "children": [
        "/langchain-chat/_langchain-chat/$id",
        "/langchain-chat/_langchain-chat/"
      ]
    },
    "/chat/_chat": {
      "filePath": "chat/_chat.tsx",
      "parent": "/chat",
      "children": [
        "/chat/_chat/$id",
        "/chat/_chat/"
      ]
    },
    "/knowledge/$id": {
      "filePath": "knowledge/$id.tsx"
    },
    "/knowledge/": {
      "filePath": "knowledge/index.tsx"
    },
    "/translate/": {
      "filePath": "translate/index.tsx"
    },
    "/chat/_chat/$id": {
      "filePath": "chat/_chat.$id.tsx",
      "parent": "/chat/_chat"
    },
    "/langchain-chat/_langchain-chat/$id": {
      "filePath": "langchain-chat/_langchain-chat.$id.tsx",
      "parent": "/langchain-chat"
    },
    "/chat/_chat/": {
      "filePath": "chat/_chat.index.tsx",
      "parent": "/chat/_chat"
    },
    "/langchain-chat/_langchain-chat/": {
      "filePath": "langchain-chat/_langchain-chat.index.tsx",
      "parent": "/langchain-chat"
    }
  }
}
ROUTE_MANIFEST_END */
