/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ChatImport } from './routes/chat'
import { Route as IndexImport } from './routes/index'
import { Route as ChatChatImport } from './routes/chat/_chat'
import { Route as ChatChatIndexImport } from './routes/chat/_chat.index'
import { Route as ChatChatIdImport } from './routes/chat/_chat.$id'

// Create/Update Routes

const ChatRoute = ChatImport.update({
  path: '/chat',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ChatChatRoute = ChatChatImport.update({
  id: '/_chat',
  getParentRoute: () => ChatRoute,
} as any)

const ChatChatIndexRoute = ChatChatIndexImport.update({
  path: '/',
  getParentRoute: () => ChatChatRoute,
} as any)

const ChatChatIdRoute = ChatChatIdImport.update({
  path: '/$id',
  getParentRoute: () => ChatChatRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatImport
      parentRoute: typeof rootRoute
    }
    '/chat/_chat': {
      id: '/chat/_chat'
      path: ''
      fullPath: '/chat'
      preLoaderRoute: typeof ChatChatImport
      parentRoute: typeof ChatImport
    }
    '/chat/_chat/$id': {
      id: '/chat/_chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatChatIdImport
      parentRoute: typeof ChatChatImport
    }
    '/chat/_chat/': {
      id: '/chat/_chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatChatIndexImport
      parentRoute: typeof ChatChatImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ChatRoute: ChatRoute.addChildren({
    ChatChatRoute: ChatChatRoute.addChildren({
      ChatChatIdRoute,
      ChatChatIndexRoute,
    }),
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/chat"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/chat": {
      "filePath": "chat.tsx",
      "children": [
        "/chat/_chat"
      ]
    },
    "/chat/_chat": {
      "filePath": "chat/_chat.tsx",
      "parent": "/chat",
      "children": [
        "/chat/_chat/$id",
        "/chat/_chat/"
      ]
    },
    "/chat/_chat/$id": {
      "filePath": "chat/_chat.$id.tsx",
      "parent": "/chat/_chat"
    },
    "/chat/_chat/": {
      "filePath": "chat/_chat.index.tsx",
      "parent": "/chat/_chat"
    }
  }
}
ROUTE_MANIFEST_END */
